/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cashmachine;

public class App {

    public static void main(String[] args) {
        Hardware hw = new Hardware();
        
        while (hw.cardIsInserted()) {

        }
    }
}
