/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cashmachine;

import java.util.Scanner;

public class CashMachine {

    public static void main(String[] args) {
        Hardware hw = new Hardware();
        CashMachine cm = new CashMachine();
        Bank bank = new Bank();

        boolean unlocked = false;
        boolean depositing = false;
        boolean withdrawing = false;
        boolean ejecting = false;

        Scanner scanner = new Scanner(System.in);

        while (hw.cardIsInserted()) {
            
            if (!unlocked) {
                System.out.println("Welcome to " + getMachineOwner() + "!");
                System.out.println("Enter PIN: ");
                String pin = scanner.next();
                unlocked = bank.validPin(hw.getCardID(), pin);
            }

            if (unlocked) {

                if (depositing) {
                    System.out.println("Enter amount to deposit: ");
                    int amount = scanner.nextInt();

                    if (hw.receivedMoney(amount)) {
                        bank.deposit(amount);
                    }
                    depositing = false;
                }

                if (withdrawing) {
                    System.out.println("Enter amount to withdraw: ");
                    int amount = scanner.nextInt();
                    
                    if (amount <= bank.getBalance()) {
                        bank.withdraw(amount);
                        hw.dispenseMoney(amount);
                    }
                    
                    withdrawing = false;
                }

                System.out.println("[1] - Check balance");
                System.out.println("[2] - Withdraw");
                System.out.println("[3] - Deposit");
                System.out.println("[4] - Exit");
                String choice = scanner.next();

                switch(choice) {
                    case "1":
                        System.out.println("Balance: " + bank.getBalance());
                        break;
                    case "2":
                        depositing = true;
                        break;
                    case "3":
                        withdrawing = true;
                        break;
                    case "4":
                        hw.ejectCard();
                        break;
                }
            }



        }
        scanner.close();
    }

    private static String getMachineOwner () {
        return Bank.getName();
    }
}

